/* ═══════════════════════════════════════════════════════════════════════════
 * AiSheetSetupPage.jsx -- Intermediate page for publishing AI-generated sheets.
 *
 * Reached via /sheets/new/lab with location.state = {
 *   aiGeneratedHtml: string,   -- the full HTML document
 *   suggestedTitle:  string,   -- suggested title from conversation
 *   source:          'hub-ai', -- provenance marker
 * }
 *
 * Shows a split view: left side has title/course/description form,
 * right side shows a live preview of the AI-generated HTML.
 * On submit, creates the sheet via POST /api/sheets and redirects to
 * /sheets/:id/lab so the student can refine it in the full Sheet Lab.
 * ═══════════════════════════════════════════════════════════════════════════ */
import { useState, useEffect, useCallback, useMemo } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import Navbar from '../../../components/navbar/Navbar'
import AppSidebar from '../../../components/sidebar/AppSidebar'
import { IconSpark, IconSheets, IconSpinner } from '../../../components/Icons'
import { useProtectedPage } from '../../../lib/useProtectedPage'
import { useResponsiveAppLayout } from '../../../lib/ui'
import { usePageTitle } from '../../../lib/usePageTitle'
import { pageShell } from '../../../lib/ui'
import { API } from '../../../config'
import { PAGE_FONT, authHeaders } from '../../shared/pageUtils'
import { useSession } from '../../../lib/session-context'
import { enrolledSchoolIdsFromUser, flattenSchoolsToCourses } from '../../../lib/courses'
import CourseSelect from '../../../components/CourseSelect'

export default function AiSheetSetupPage() {
  usePageTitle('Publish AI Sheet')
  const { status: authStatus } = useProtectedPage()
  const layout = useResponsiveAppLayout()
  const location = useLocation()
  const navigate = useNavigate()

  // Read AI-generated content from navigation state.
  const aiState = location.state || {}
  const aiHtml = aiState.aiGeneratedHtml || ''
  const suggestedTitle = aiState.suggestedTitle || ''

  // Redirect if no AI content was passed (e.g. direct URL visit).
  useEffect(() => {
    if (!aiHtml && authStatus === 'ready') {
      navigate('/ai', { replace: true })
    }
  }, [aiHtml, authStatus, navigate])

  // Form state.
  const [title, setTitle] = useState(suggestedTitle)
  const [description, setDescription] = useState('Generated by Hub AI')
  const [courseId, setCourseId] = useState('')
  const [courses, setCourses] = useState([])
  const [loadingCourses, setLoadingCourses] = useState(true)
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState('')
  const { user } = useSession()
  const enrolledSchoolIds = useMemo(() => enrolledSchoolIdsFromUser(user), [user])

  // Fetch enrolled courses.
  const loadCourses = useCallback(async () => {
    try {
      const res = await fetch(`${API}/api/courses/schools`, {
        headers: authHeaders(),
        credentials: 'include',
      })
      const data = await res.json().catch(() => [])
      setCourses(flattenSchoolsToCourses(data))
    } catch {
      setCourses([])
    } finally {
      setLoadingCourses(false)
    }
  }, [])

  useEffect(() => {
    loadCourses()
  }, [loadCourses])

  // Preview iframe source.
  const previewSrc = useMemo(() => {
    if (!aiHtml) return ''
    const isFullDoc = /^\s*<!DOCTYPE/i.test(aiHtml) || /^\s*<html/i.test(aiHtml)
    const doc = isFullDoc
      ? aiHtml
      : `<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
body { font-family: system-ui, sans-serif; padding: 24px; color: #1a1a2e; line-height: 1.7; }
</style></head><body>${aiHtml}</body></html>`
    return `data:text/html;charset=utf-8,${encodeURIComponent(doc)}`
  }, [aiHtml])

  // Submit: create sheet and redirect to Lab.
  const handleSubmit = async () => {
    setError('')
    if (!title.trim()) {
      setError('Title is required.')
      return
    }
    if (!courseId) {
      setError('Please select a course.')
      return
    }

    setSubmitting(true)
    try {
      const res = await fetch(`${API}/api/sheets`, {
        method: 'POST',
        headers: { ...authHeaders(), 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({
          title: title.trim(),
          description: description.trim(),
          content: aiHtml,
          contentFormat: 'html',
          courseId: parseInt(courseId, 10),
          status: 'draft',
        }),
      })
      if (!res.ok) {
        const data = await res.json().catch(() => ({}))
        throw new Error(data.error || 'Failed to create sheet.')
      }
      const sheet = await res.json()
      navigate(`/sheets/${sheet.id}/lab`, { replace: true })
    } catch (err) {
      setError(err.message)
      setSubmitting(false)
    }
  }

  if (authStatus !== 'ready' || !aiHtml) {
    return (
      <div style={{ minHeight: '100vh', background: 'var(--sh-bg)', fontFamily: PAGE_FONT }}>
        <Navbar />
        <div
          style={{
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            minHeight: 400,
          }}
        >
          <div style={{ textAlign: 'center', color: 'var(--sh-muted)' }}>
            <IconSpinner
              size={24}
              style={{ animation: 'spin 1s linear infinite', marginBottom: 12 }}
            />
            <div style={{ fontSize: 14 }}>Preparing AI sheet...</div>
          </div>
        </div>
      </div>
    )
  }

  const isCompact = layout.isCompact

  return (
    <div
      style={{
        minHeight: '100vh',
        background: 'var(--sh-bg)',
        fontFamily: PAGE_FONT,
        overflowX: 'hidden',
      }}
    >
      <Navbar />
      <div style={pageShell('app')}>
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: layout.columns.appTwoColumn,
            gap: 20,
            alignItems: 'start',
          }}
        >
          <div
            style={{ position: isCompact ? 'static' : 'sticky', top: isCompact ? undefined : 74 }}
          >
            <AppSidebar mode={layout.sidebarMode} />
          </div>
          <main id="main-content">
            {/* Header */}
            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 10,
                marginBottom: 16,
              }}
            >
              <div
                style={{
                  width: 36,
                  height: 36,
                  borderRadius: '50%',
                  background: 'linear-gradient(135deg, var(--sh-brand), #7c3aed)',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                <IconSpark size={18} style={{ color: '#fff' }} />
              </div>
              <div>
                <h1
                  style={{ fontSize: 18, fontWeight: 800, color: 'var(--sh-heading)', margin: 0 }}
                >
                  Publish AI-Generated Sheet
                </h1>
                <p style={{ fontSize: 12, color: 'var(--sh-muted)', margin: 0 }}>
                  Add details and choose a course, then open in Sheet Lab to refine.
                </p>
              </div>
            </div>

            {/* Error */}
            {error && (
              <div
                style={{
                  background: 'var(--sh-danger-bg)',
                  border: '1px solid var(--sh-danger-border)',
                  borderRadius: 10,
                  padding: '10px 14px',
                  marginBottom: 12,
                  fontSize: 13,
                  color: 'var(--sh-danger-text)',
                }}
              >
                {error}
              </div>
            )}

            {/* Main layout: form + preview */}
            <div
              style={{
                display: 'grid',
                gridTemplateColumns: isCompact ? '1fr' : '340px 1fr',
                gap: 16,
                alignItems: 'start',
              }}
            >
              {/* Left: Form */}
              <div
                style={{
                  background: 'var(--sh-surface)',
                  borderRadius: 14,
                  border: '1px solid var(--sh-border)',
                  padding: '20px',
                }}
              >
                {/* Title */}
                <div style={{ marginBottom: 14 }}>
                  <label
                    style={{
                      fontSize: 10,
                      fontWeight: 700,
                      color: 'var(--sh-slate-500)',
                      letterSpacing: '.06em',
                      display: 'block',
                      marginBottom: 5,
                    }}
                  >
                    SHEET TITLE
                  </label>
                  <input
                    value={title}
                    onChange={(e) => setTitle(e.target.value)}
                    placeholder="e.g. Organic Chemistry Reactions"
                    style={{
                      width: '100%',
                      padding: '8px 12px',
                      border: `1.5px solid ${error && !title.trim() ? 'var(--sh-danger-border)' : 'var(--sh-border)'}`,
                      borderRadius: 8,
                      fontSize: 13,
                      fontFamily: PAGE_FONT,
                      outline: 'none',
                      color: 'var(--sh-text)',
                      boxSizing: 'border-box',
                    }}
                  />
                </div>

                {/* Course */}
                <div style={{ marginBottom: 14 }}>
                  <label
                    style={{
                      fontSize: 10,
                      fontWeight: 700,
                      color: 'var(--sh-slate-500)',
                      letterSpacing: '.06em',
                      display: 'block',
                      marginBottom: 5,
                    }}
                  >
                    COURSE
                  </label>
                  {loadingCourses ? (
                    <div style={{ fontSize: 12, color: 'var(--sh-muted)', padding: '8px 0' }}>
                      Loading courses...
                    </div>
                  ) : (
                    <CourseSelect
                      courses={courses}
                      enrolledSchoolIds={enrolledSchoolIds}
                      value={courseId}
                      onChange={(e) => setCourseId(e.target.value)}
                      ariaLabel="Course"
                      placeholderLabel="Select a course..."
                      style={{
                        width: '100%',
                        padding: '8px 12px',
                        border: `1.5px solid ${error && !courseId ? 'var(--sh-danger-border)' : 'var(--sh-border)'}`,
                        borderRadius: 8,
                        fontSize: 13,
                        fontFamily: PAGE_FONT,
                        outline: 'none',
                        color: courseId ? 'var(--sh-text)' : 'var(--sh-muted)',
                        boxSizing: 'border-box',
                      }}
                    />
                  )}
                  {courses.length === 0 && !loadingCourses && (
                    <div style={{ fontSize: 11, color: 'var(--sh-warning-text)', marginTop: 4 }}>
                      No courses found.{' '}
                      <a href="/my-courses" style={{ color: 'var(--sh-brand)', fontWeight: 600 }}>
                        Add courses
                      </a>{' '}
                      first.
                    </div>
                  )}
                </div>

                {/* Description */}
                <div style={{ marginBottom: 18 }}>
                  <label
                    style={{
                      fontSize: 10,
                      fontWeight: 700,
                      color: 'var(--sh-slate-500)',
                      letterSpacing: '.06em',
                      display: 'block',
                      marginBottom: 5,
                    }}
                  >
                    DESCRIPTION
                  </label>
                  <textarea
                    value={description}
                    onChange={(e) => setDescription(e.target.value.slice(0, 300))}
                    rows={3}
                    maxLength={300}
                    placeholder="Brief summary of what this sheet covers..."
                    style={{
                      width: '100%',
                      padding: '8px 12px',
                      border: '1.5px solid var(--sh-border)',
                      borderRadius: 8,
                      fontSize: 13,
                      fontFamily: PAGE_FONT,
                      outline: 'none',
                      color: 'var(--sh-text)',
                      boxSizing: 'border-box',
                      resize: 'none',
                      lineHeight: 1.6,
                    }}
                  />
                  <div
                    style={{
                      fontSize: 10,
                      color: 'var(--sh-muted)',
                      textAlign: 'right',
                      marginTop: 3,
                    }}
                  >
                    {description.length}/300
                  </div>
                </div>

                {/* Submit */}
                <button
                  onClick={handleSubmit}
                  disabled={submitting || !title.trim() || !courseId}
                  style={{
                    width: '100%',
                    padding: '10px 16px',
                    background: title.trim() && courseId ? 'var(--sh-brand)' : 'var(--sh-soft)',
                    color: title.trim() && courseId ? '#fff' : 'var(--sh-muted)',
                    border: 'none',
                    borderRadius: 10,
                    fontSize: 13,
                    fontWeight: 700,
                    cursor: title.trim() && courseId && !submitting ? 'pointer' : 'not-allowed',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: 8,
                    fontFamily: PAGE_FONT,
                  }}
                >
                  {submitting ? (
                    <>
                      <IconSpinner size={14} style={{ animation: 'spin 1s linear infinite' }} />
                      Creating sheet...
                    </>
                  ) : (
                    <>
                      <IconSheets size={14} />
                      Create and Open in Sheet Lab
                    </>
                  )}
                </button>

                <p
                  style={{ fontSize: 11, color: 'var(--sh-muted)', marginTop: 10, lineHeight: 1.5 }}
                >
                  Your sheet will be created as a private draft. You can edit it in the Sheet Lab
                  and publish when ready.
                </p>
              </div>

              {/* Right: Preview */}
              <div
                style={{
                  background: 'var(--sh-surface)',
                  borderRadius: 14,
                  border: '1px solid var(--sh-border)',
                  overflow: 'hidden',
                  height: isCompact ? 400 : 'calc(100vh - 200px)',
                }}
              >
                <div
                  style={{
                    padding: '10px 16px',
                    borderBottom: '1px solid var(--sh-border)',
                    display: 'flex',
                    alignItems: 'center',
                    gap: 8,
                    background: 'var(--sh-soft)',
                  }}
                >
                  <IconSheets size={14} style={{ color: 'var(--sh-brand)' }} />
                  <span style={{ fontSize: 12, fontWeight: 700, color: 'var(--sh-heading)' }}>
                    Sheet Preview
                  </span>
                </div>
                <iframe
                  src={previewSrc}
                  // Strictest sandbox for an AI-generated `data:` URI
                  // preview. `data:` URIs always have an opaque origin so
                  // `allow-same-origin` is a no-op today, but per CLAUDE.md
                  // A14 leaving it on the attribute re-introduces the
                  // sandbox-escape vector if a future refactor swaps the
                  // src to a `blob:` or backend URL. This is a static
                  // preview — no scripts, no forms, no popups needed.
                  sandbox=""
                  title="AI Sheet Preview"
                  style={{ width: '100%', height: 'calc(100% - 40px)', border: 'none' }}
                />
              </div>
            </div>
          </main>
        </div>
      </div>
    </div>
  )
}
