// Courses for public universities (excluding UMD which is in catalogCourses_major.js)

const COURSES_PUBLIC = {
  // UMBC (40 courses)
  UMBC: [
    { name: 'Introduction to Computer Science I', code: 'CMSC201', department: 'Computer Science' },
    {
      name: 'Introduction to Computer Science II',
      code: 'CMSC202',
      department: 'Computer Science',
    },
    { name: 'Discrete Structures', code: 'CMSC203', department: 'Computer Science' },
    { name: 'Computer Organization', code: 'CMSC313', department: 'Computer Science' },
    { name: 'Data Structures', code: 'CMSC341', department: 'Computer Science' },
    { name: 'Algorithms', code: 'CMSC441', department: 'Computer Science' },
    { name: 'Software Engineering', code: 'CMSC345', department: 'Computer Science' },
    { name: 'Database Management', code: 'CMSC461', department: 'Computer Science' },
    { name: 'Operating Systems', code: 'CMSC421', department: 'Computer Science' },
    { name: 'Web Development', code: 'CMSC331', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH151', department: 'Mathematics' },
    { name: 'Calculus II', code: 'MATH152', department: 'Mathematics' },
    { name: 'Linear Algebra', code: 'MATH221', department: 'Mathematics' },
    { name: 'Discrete Mathematics', code: 'MATH281', department: 'Mathematics' },
    { name: 'Differential Equations', code: 'MATH251', department: 'Mathematics' },
    { name: 'General Chemistry I', code: 'CHEM101', department: 'Chemistry' },
    { name: 'General Chemistry II', code: 'CHEM102', department: 'Chemistry' },
    { name: 'Organic Chemistry I', code: 'CHEM231', department: 'Chemistry' },
    { name: 'Physics I', code: 'PHYS121', department: 'Physics' },
    { name: 'Physics II', code: 'PHYS122', department: 'Physics' },
    { name: 'Biology I', code: 'BIOL100', department: 'Biology' },
    { name: 'Biology II', code: 'BIOL101', department: 'Biology' },
    { name: 'English Composition', code: 'ENGL101', department: 'English' },
    { name: 'Literature and Rhetoric', code: 'ENGL201', department: 'English' },
    { name: 'American History', code: 'HIST101', department: 'History' },
    { name: 'World History', code: 'HIST102', department: 'History' },
    { name: 'Introduction to Psychology', code: 'PSYC100', department: 'Psychology' },
    { name: 'Principles of Economics', code: 'ECON101', department: 'Economics' },
    { name: 'Microeconomics', code: 'ECON201', department: 'Economics' },
    { name: 'Technical Communication', code: 'ENGL393', department: 'English' },
    { name: 'Statistics for Scientists', code: 'STAT355', department: 'Statistics' },
    { name: 'Information Systems', code: 'CMSC380', department: 'Computer Science' },
    { name: 'Computer Networks', code: 'CMSC411', department: 'Computer Science' },
    { name: 'Artificial Intelligence', code: 'CMSC451', department: 'Computer Science' },
    { name: 'Machine Learning', code: 'CMSC471', department: 'Computer Science' },
    { name: 'Data Mining', code: 'CMSC491', department: 'Computer Science' },
    { name: 'Business Law', code: 'BUSN301', department: 'Business' },
    { name: 'Marketing Principles', code: 'MKTG201', department: 'Marketing' },
    { name: 'Accounting Principles I', code: 'ACCT201', department: 'Accounting' },
    { name: 'Management Essentials', code: 'MGMT201', department: 'Management' },
  ],

  // TOWSON UNIVERSITY (25 courses)
  TU: [
    { name: 'Computer Science I', code: 'COSC101', department: 'Computer Science' },
    { name: 'Computer Science II', code: 'COSC102', department: 'Computer Science' },
    { name: 'Data Structures', code: 'COSC201', department: 'Computer Science' },
    { name: 'Database Systems', code: 'COSC301', department: 'Computer Science' },
    { name: 'Web Programming', code: 'COSC311', department: 'Computer Science' },
    { name: 'Software Engineering', code: 'COSC340', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH115', department: 'Mathematics' },
    { name: 'Calculus II', code: 'MATH116', department: 'Mathematics' },
    { name: 'Linear Algebra', code: 'MATH213', department: 'Mathematics' },
    { name: 'Discrete Mathematics', code: 'MATH215', department: 'Mathematics' },
    { name: 'General Physics I', code: 'PHYS155', department: 'Physics' },
    { name: 'General Physics II', code: 'PHYS156', department: 'Physics' },
    { name: 'General Chemistry I', code: 'CHEM101', department: 'Chemistry' },
    { name: 'General Chemistry II', code: 'CHEM102', department: 'Chemistry' },
    { name: 'Biology I', code: 'BIOL101', department: 'Biology' },
    { name: 'Biology II', code: 'BIOL102', department: 'Biology' },
    { name: 'English Composition', code: 'ENGL101', department: 'English' },
    { name: 'Literature Survey', code: 'ENGL201', department: 'English' },
    { name: 'American History I', code: 'HIST101', department: 'History' },
    { name: 'American History II', code: 'HIST102', department: 'History' },
    { name: 'World History I', code: 'HIST103', department: 'History' },
    { name: 'Introduction to Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Principles of Economics', code: 'ECON103', department: 'Economics' },
    { name: 'Introductory Business', code: 'MGMT101', department: 'Management' },
    { name: 'Accounting Principles I', code: 'ACCT101', department: 'Accounting' },
  ],

  // MORGAN STATE UNIVERSITY (20 courses)
  Morgan: [
    { name: 'Introduction to Computer Science', code: 'CSCI111', department: 'Computer Science' },
    { name: 'Computer Science II', code: 'CSCI112', department: 'Computer Science' },
    { name: 'Data Structures', code: 'CSCI211', department: 'Computer Science' },
    { name: 'Programming Concepts', code: 'CSCI105', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH131', department: 'Mathematics' },
    { name: 'Calculus II', code: 'MATH132', department: 'Mathematics' },
    { name: 'Linear Algebra', code: 'MATH231', department: 'Mathematics' },
    { name: 'General Physics I', code: 'PHYS200', department: 'Physics' },
    { name: 'General Physics II', code: 'PHYS201', department: 'Physics' },
    { name: 'General Chemistry I', code: 'CHEM101', department: 'Chemistry' },
    { name: 'General Chemistry II', code: 'CHEM102', department: 'Chemistry' },
    { name: 'Biology I', code: 'BIOL101', department: 'Biology' },
    { name: 'Biology II', code: 'BIOL102', department: 'Biology' },
    { name: 'English Composition', code: 'ENGL101', department: 'English' },
    { name: 'Literature and Culture', code: 'ENGL201', department: 'English' },
    { name: 'World History', code: 'HIST102', department: 'History' },
    { name: 'African American History', code: 'HIST315', department: 'History' },
    { name: 'Introduction to Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Microeconomics', code: 'ECON201', department: 'Economics' },
    { name: 'Macroeconomics', code: 'ECON202', department: 'Economics' },
  ],

  // BOWIE STATE UNIVERSITY (14 courses)
  Bowie: [
    { name: 'Intro to Computer Science', code: 'CSCI101', department: 'Computer Science' },
    { name: 'Computer Science II', code: 'CSCI102', department: 'Computer Science' },
    { name: 'Programming I', code: 'CSCI105', department: 'Computer Science' },
    { name: 'Data Structures', code: 'CSCI201', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH121', department: 'Mathematics' },
    { name: 'Calculus II', code: 'MATH122', department: 'Mathematics' },
    { name: 'Physics for Engineers', code: 'PHYS211', department: 'Physics' },
    { name: 'General Chemistry', code: 'CHEM101', department: 'Chemistry' },
    { name: 'Biology I', code: 'BIOL101', department: 'Biology' },
    { name: 'English Composition', code: 'ENGL101', department: 'English' },
    { name: 'American History', code: 'HIST101', department: 'History' },
    { name: 'Introduction to Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'General Economics', code: 'ECON101', department: 'Economics' },
    { name: 'Business Management', code: 'MGMT101', department: 'Management' },
  ],

  // COPPIN STATE UNIVERSITY (12 courses)
  Coppin: [
    { name: 'Introduction to Computer Science', code: 'CS101', department: 'Computer Science' },
    { name: 'Programming I', code: 'CS105', department: 'Computer Science' },
    { name: 'Programming II', code: 'CS106', department: 'Computer Science' },
    { name: 'Web Development', code: 'CS210', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH121', department: 'Mathematics' },
    { name: 'General Physics', code: 'PHYS201', department: 'Physics' },
    { name: 'General Chemistry', code: 'CHEM101', department: 'Chemistry' },
    { name: 'Biology I', code: 'BIOL101', department: 'Biology' },
    { name: 'English Composition', code: 'ENGL101', department: 'English' },
    { name: 'World History', code: 'HIST102', department: 'History' },
    { name: 'Introduction to Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Introduction to Economics', code: 'ECON101', department: 'Economics' },
  ],

  // SALISBURY UNIVERSITY (15 courses)
  SU: [
    { name: 'Computer Science I', code: 'COSC171', department: 'Computer Science' },
    { name: 'Computer Science II', code: 'COSC172', department: 'Computer Science' },
    { name: 'Data Structures', code: 'COSC250', department: 'Computer Science' },
    { name: 'Database Management', code: 'COSC470', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH161', department: 'Mathematics' },
    { name: 'Calculus II', code: 'MATH162', department: 'Mathematics' },
    { name: 'Linear Algebra', code: 'MATH260', department: 'Mathematics' },
    { name: 'General Physics I', code: 'PHYS161', department: 'Physics' },
    { name: 'General Chemistry I', code: 'CHEM191', department: 'Chemistry' },
    { name: 'Biology I', code: 'BIOL161', department: 'Biology' },
    { name: 'English Composition', code: 'ENGL101', department: 'English' },
    { name: 'American Literature', code: 'ENGL321', department: 'English' },
    { name: 'U.S. History I', code: 'HIST105', department: 'History' },
    { name: 'Introduction to Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Microeconomics', code: 'ECON201', department: 'Economics' },
  ],

  // FROSTBURG STATE UNIVERSITY (11 courses)
  FSU: [
    { name: 'Introduction to CS', code: 'CSCI100', department: 'Computer Science' },
    { name: 'Programming I', code: 'CSCI105', department: 'Computer Science' },
    { name: 'Programming II', code: 'CSCI106', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH121', department: 'Mathematics' },
    { name: 'Physics I', code: 'PHYS150', department: 'Physics' },
    { name: 'Chemistry I', code: 'CHEM150', department: 'Chemistry' },
    { name: 'Biology I', code: 'BIOL150', department: 'Biology' },
    { name: 'English Composition', code: 'ENGL101', department: 'English' },
    { name: 'World History', code: 'HIST101', department: 'History' },
    { name: 'Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Economics I', code: 'ECON101', department: 'Economics' },
  ],

  // UNIVERSITY OF BALTIMORE (10 courses)
  UBalt: [
    { name: 'Introduction to Programming', code: 'CMPT101', department: 'Information Technology' },
    { name: 'Web Development', code: 'CMPT201', department: 'Information Technology' },
    { name: 'Database Fundamentals', code: 'CMPT210', department: 'Information Technology' },
    { name: 'Business Mathematics', code: 'MATH101', department: 'Mathematics' },
    { name: 'Technical Writing', code: 'ENGL200', department: 'English' },
    { name: 'American History', code: 'HIST101', department: 'History' },
    { name: 'Organizational Behavior', code: 'MGMT201', department: 'Management' },
    { name: 'Financial Accounting', code: 'ACCT201', department: 'Accounting' },
    { name: 'Business Law', code: 'LAW201', department: 'Business Law' },
    { name: 'Marketing Principles', code: 'MKTG201', department: 'Marketing' },
  ],

  // UNIVERSITY OF MARYLAND EASTERN SHORE (10 courses)
  UMES: [
    { name: 'Introduction to CS', code: 'CSCI101', department: 'Computer Science' },
    { name: 'Programming Fundamentals', code: 'CSCI105', department: 'Computer Science' },
    { name: 'Calculus I', code: 'MATH131', department: 'Mathematics' },
    { name: 'General Physics', code: 'PHYS201', department: 'Physics' },
    { name: 'General Chemistry', code: 'CHEM101', department: 'Chemistry' },
    { name: 'Biology I', code: 'BIOL101', department: 'Biology' },
    { name: 'English Composition', code: 'ENGL101', department: 'English' },
    { name: 'History', code: 'HIST101', department: 'History' },
    { name: 'Psychology', code: 'PSYC101', department: 'Psychology' },
    { name: 'Economics', code: 'ECON101', department: 'Economics' },
  ],

  // UNIVERSITY OF MARYLAND GLOBAL CAMPUS (8 courses)
  UMGC: [
    { name: 'Introduction to Technology', code: 'ITEC101', department: 'Information Technology' },
    { name: 'Business Management', code: 'MGMT301', department: 'Management' },
    { name: 'Financial Accounting', code: 'ACCT311', department: 'Accounting' },
    { name: 'Business Law', code: 'CMIT301', department: 'Information Technology' },
    { name: 'Database Design', code: 'CMIT415', department: 'Information Technology' },
    { name: 'Business Communications', code: 'COMM101', department: 'Communication' },
    { name: 'Economics for Managers', code: 'ECON201', department: 'Economics' },
    { name: 'Organizational Behavior', code: 'MGMT325', department: 'Management' },
  ],
}

module.exports = { COURSES_PUBLIC }
