// Courses for major research universities (UMD, JHU)

const COURSES_MAJOR = {
  // UNIVERSITY OF MARYLAND, COLLEGE PARK (Major Research University - 70+ courses)
  UMD: [
    // Computer Science (16 courses)
    { name: 'Introduction to C Programming', code: 'CMSC106', department: 'Computer Science' },
    { name: 'Object-Oriented Programming I', code: 'CMSC131', department: 'Computer Science' },
    { name: 'Object-Oriented Programming II', code: 'CMSC132', department: 'Computer Science' },
    { name: 'Introduction to Computer Systems', code: 'CMSC216', department: 'Computer Science' },
    { name: 'Discrete Structures', code: 'CMSC250', department: 'Computer Science' },
    { name: 'Introduction to Data Science', code: 'CMSC320', department: 'Computer Science' },
    {
      name: 'Organization of Programming Languages',
      code: 'CMSC330',
      department: 'Computer Science',
    },
    { name: 'Web Application Development', code: 'CMSC335', department: 'Computer Science' },
    { name: 'Algorithms', code: 'CMSC351', department: 'Computer Science' },
    { name: 'Computer Graphics', code: 'CMSC425', department: 'Computer Science' },
    { name: 'Human-Computer Interaction', code: 'CMSC434', department: 'Computer Science' },
    { name: 'Database Management Systems', code: 'CMSC461', department: 'Computer Science' },
    { name: 'Artificial Intelligence', code: 'CMSC421', department: 'Computer Science' },
    { name: 'Machine Learning', code: 'CMSC422', department: 'Computer Science' },
    { name: 'Computer Networks', code: 'CMSC414', department: 'Computer Science' },
    { name: 'Software Engineering', code: 'CMSC435', department: 'Computer Science' },

    // Mathematics (14 courses)
    { name: 'Precalculus', code: 'MATH115', department: 'Mathematics' },
    { name: 'Elementary Calculus I', code: 'MATH120', department: 'Mathematics' },
    { name: 'Elementary Calculus II', code: 'MATH121', department: 'Mathematics' },
    { name: 'Calculus I', code: 'MATH140', department: 'Mathematics' },
    { name: 'Calculus II', code: 'MATH141', department: 'Mathematics' },
    { name: 'Calculus III', code: 'MATH241', department: 'Mathematics' },
    { name: 'Linear Algebra', code: 'MATH240', department: 'Mathematics' },
    { name: 'Discrete Mathematics for Life Sciences', code: 'MATH135', department: 'Mathematics' },
    { name: 'Applied Mathematics for Engineering', code: 'MATH246', department: 'Mathematics' },
    { name: 'Abstract Algebra I', code: 'MATH310', department: 'Mathematics' },
    { name: 'Real Analysis I', code: 'MATH320', department: 'Mathematics' },
    { name: 'Complex Analysis', code: 'MATH410', department: 'Mathematics' },
    { name: 'Differential Equations', code: 'MATH341', department: 'Mathematics' },
    { name: 'Numerical Methods', code: 'MATH461', department: 'Mathematics' },

    // Physics (12 courses)
    { name: 'Physics of Music', code: 'PHYS102', department: 'Physics' },
    { name: 'Light and Photography', code: 'PHYS106', department: 'Physics' },
    { name: 'Physics in the Modern World', code: 'PHYS111', department: 'Physics' },
    { name: 'Fundamentals of Physics I', code: 'PHYS121', department: 'Physics' },
    { name: 'Fundamentals of Physics II', code: 'PHYS122', department: 'Physics' },
    { name: 'University Physics I', code: 'PHYS131', department: 'Physics' },
    { name: 'University Physics II', code: 'PHYS132', department: 'Physics' },
    { name: 'Physics for Engineering I', code: 'PHYS141', department: 'Physics' },
    { name: 'Physics for Engineering II', code: 'PHYS142', department: 'Physics' },
    { name: 'Modern Physics', code: 'PHYS260', department: 'Physics' },
    { name: 'Optics', code: 'PHYS320', department: 'Physics' },
    { name: 'Thermodynamics', code: 'PHYS401', department: 'Physics' },

    // Chemistry (12 courses)
    { name: 'Chemistry I - General Chemistry', code: 'CHEM131', department: 'Chemistry' },
    { name: 'General Chemistry I Laboratory', code: 'CHEM132', department: 'Chemistry' },
    { name: 'General Chemistry for Engineers', code: 'CHEM135', department: 'Chemistry' },
    { name: 'Principles of General Chemistry', code: 'CHEM146', department: 'Chemistry' },
    { name: 'Chemistry II - Organic Chemistry', code: 'CHEM231', department: 'Chemistry' },
    { name: 'Organic Chemistry Laboratory', code: 'CHEM232', department: 'Chemistry' },
    { name: 'Organic Chemistry Reaction Mechanisms', code: 'CHEM341', department: 'Chemistry' },
    { name: 'Physical Chemistry I', code: 'CHEM351', department: 'Chemistry' },
    { name: 'Analytical Chemistry', code: 'CHEM421', department: 'Chemistry' },
    { name: 'Biochemistry I', code: 'CHEM431', department: 'Chemistry' },
    { name: 'Biochemistry II', code: 'CHEM432', department: 'Chemistry' },
    { name: 'Inorganic Chemistry', code: 'CHEM441', department: 'Chemistry' },

    // Biology (12 courses)
    { name: 'The World of Biology', code: 'BSCI103', department: 'Biology' },
    { name: 'Insects', code: 'BSCI120', department: 'Biology' },
    { name: 'Plant Biology for Non-Science Students', code: 'BSCI124', department: 'Biology' },
    { name: 'General Biology I', code: 'BSCI170', department: 'Biology' },
    { name: 'General Biology II', code: 'BSCI171', department: 'Biology' },
    { name: 'Cell Biology and Molecular Genetics', code: 'BSCI272', department: 'Biology' },
    { name: 'Genetics', code: 'BSCI370', department: 'Biology' },
    { name: 'Ecology', code: 'BSCI330', department: 'Biology' },
    { name: 'Evolution', code: 'BSCI340', department: 'Biology' },
    { name: 'Molecular Biology', code: 'BSCI375', department: 'Biology' },
    { name: 'Physiology', code: 'BSCI380', department: 'Biology' },
    { name: 'Developmental Biology', code: 'BSCI420', department: 'Biology' },

    // English (14 courses)
    { name: 'Academic Writing', code: 'ENGL101', department: 'English' },
    { name: 'Shakespeare and Identity', code: 'ENGL120', department: 'English' },
    { name: 'Renaissance Lyric and Song', code: 'ENGL121', department: 'English' },
    { name: 'Why Poetry Matters', code: 'ENGL125', department: 'English' },
    { name: 'Why Fiction Matters', code: 'ENGL126', department: 'English' },
    { name: 'British Literature I', code: 'ENGL242', department: 'English' },
    { name: 'British Literature II', code: 'ENGL243', department: 'English' },
    { name: 'American Literature I', code: 'ENGL245', department: 'English' },
    { name: 'American Literature II', code: 'ENGL246', department: 'English' },
    { name: 'World Literature I', code: 'ENGL248', department: 'English' },
    { name: 'World Literature II', code: 'ENGL249', department: 'English' },
    { name: 'Technical Writing', code: 'ENGL310', department: 'English' },
    { name: 'Creative Writing: Poetry', code: 'ENGL391', department: 'English' },
    { name: 'Creative Writing: Fiction', code: 'ENGL392', department: 'English' },

    // History (13 courses)
    { name: 'American Jewish Experience', code: 'HIST106', department: 'History' },
    { name: 'The Ancient World', code: 'HIST110', department: 'History' },
    { name: 'The Medieval World', code: 'HIST111', department: 'History' },
    { name: 'Early Modern Europe', code: 'HIST112', department: 'History' },
    { name: 'Modern Europe', code: 'HIST113', department: 'History' },
    { name: 'Colonial America', code: 'HIST121', department: 'History' },
    { name: 'Revolutionary America', code: 'HIST122', department: 'History' },
    { name: 'Civil War Era America', code: 'HIST123', department: 'History' },
    { name: 'Modern America', code: 'HIST124', department: 'History' },
    { name: 'Ancient China', code: 'HIST131', department: 'History' },
    { name: 'Modern East Asia', code: 'HIST132', department: 'History' },
    { name: 'Latin American History', code: 'HIST150', department: 'History' },
    { name: 'African History', code: 'HIST160', department: 'History' },

    // Psychology (10 courses)
    { name: 'Introduction to Psychology', code: 'PSYC100', department: 'Psychology' },
    { name: 'Statistical Methods in Psychology', code: 'PSYC200', department: 'Psychology' },
    { name: 'Introduction to Neuroscience', code: 'PSYC202', department: 'Psychology' },
    { name: 'Personality and Temperament', code: 'PSYC210', department: 'Psychology' },
    { name: 'Social Psychology', code: 'PSYC221', department: 'Psychology' },
    { name: 'Developmental Psychology', code: 'PSYC230', department: 'Psychology' },
    { name: 'Sensation and Perception', code: 'PSYC330', department: 'Psychology' },
    { name: 'Abnormal Psychology', code: 'PSYC350', department: 'Psychology' },
    { name: 'Cognitive Psychology', code: 'PSYC370', department: 'Psychology' },
    { name: 'Psychopharmacology', code: 'PSYC400', department: 'Psychology' },

    // Economics (10 courses)
    { name: 'Thinking Like an Economist', code: 'ECON111', department: 'Economics' },
    { name: 'Inequality: Determinants and Policy', code: 'ECON175', department: 'Economics' },
    { name: 'Pricing the Environment', code: 'ECON181', department: 'Economics' },
    { name: 'Energy: Crisis or Breakthrough', code: 'ECON185', department: 'Economics' },
    { name: 'Principles of Microeconomics', code: 'ECON200', department: 'Economics' },
    { name: 'Principles of Macroeconomics', code: 'ECON201', department: 'Economics' },
    { name: 'Intermediate Microeconomic Theory', code: 'ECON301', department: 'Economics' },
    { name: 'Intermediate Macroeconomic Theory', code: 'ECON303', department: 'Economics' },
    { name: 'International Economics', code: 'ECON320', department: 'Economics' },
    { name: 'Labor Economics', code: 'ECON325', department: 'Economics' },

    // Business (10 courses)
    { name: 'Introduction to Business Value Chain', code: 'BMGT110', department: 'Business' },
    { name: 'The Intentional Self', code: 'BMGT160', department: 'Business' },
    { name: 'Creative Problem Solving', code: 'BMGT161', department: 'Business' },
    { name: 'Financial Accounting', code: 'BMGT230', department: 'Business' },
    { name: 'Managerial Accounting', code: 'BMGT231', department: 'Business' },
    { name: 'Organizational Behavior', code: 'BMGT301', department: 'Business' },
    { name: 'Business Law I', code: 'BMGT320', department: 'Business' },
    { name: 'Marketing Management', code: 'BMGT370', department: 'Business' },
    { name: 'Financial Management', code: 'BMGT411', department: 'Business' },
    { name: 'Strategic Management', code: 'BMGT450', department: 'Business' },
  ],

  // JOHNS HOPKINS UNIVERSITY (Research University - 68 courses)
  JHU: [
    // Computer Science (15 courses)
    { name: 'Computer Science Foundations I', code: 'EN.601.101', department: 'Computer Science' },
    { name: 'Computer Science Foundations II', code: 'EN.601.102', department: 'Computer Science' },
    { name: 'Intermediate Programming', code: 'EN.601.220', department: 'Computer Science' },
    { name: 'Data Structures', code: 'EN.601.226', department: 'Computer Science' },
    { name: 'Computer Architecture', code: 'EN.601.241', department: 'Computer Science' },
    { name: 'Systems Programming', code: 'EN.601.414', department: 'Computer Science' },
    { name: 'Operating Systems', code: 'EN.601.415', department: 'Computer Science' },
    { name: 'Database Management Systems', code: 'EN.601.316', department: 'Computer Science' },
    { name: 'Computer Algorithms', code: 'EN.601.433', department: 'Computer Science' },
    { name: 'Software Engineering', code: 'EN.601.436', department: 'Computer Science' },
    { name: 'Network Security', code: 'EN.601.443', department: 'Computer Science' },
    { name: 'Artificial Intelligence', code: 'EN.601.461', department: 'Computer Science' },
    { name: 'Human-Computer Interaction', code: 'EN.601.468', department: 'Computer Science' },
    { name: 'Machine Learning', code: 'EN.601.475', department: 'Computer Science' },
    { name: 'Bioinformatics', code: 'EN.601.485', department: 'Computer Science' },

    // Mathematics (12 courses)
    { name: 'Calculus I', code: 'AS.110.108', department: 'Mathematics' },
    { name: 'Calculus II', code: 'AS.110.109', department: 'Mathematics' },
    { name: 'Multivariable Calculus', code: 'AS.110.202', department: 'Mathematics' },
    { name: 'Linear Algebra', code: 'AS.110.201', department: 'Mathematics' },
    { name: 'Differential Equations', code: 'AS.110.302', department: 'Mathematics' },
    { name: 'Discrete Mathematics', code: 'EN.601.230', department: 'Mathematics' },
    { name: 'Abstract Algebra I', code: 'AS.110.401', department: 'Mathematics' },
    { name: 'Real Analysis I', code: 'AS.110.405', department: 'Mathematics' },
    { name: 'Complex Analysis', code: 'AS.110.406', department: 'Mathematics' },
    { name: 'Topology', code: 'AS.110.411', department: 'Mathematics' },
    { name: 'Probability and Statistics', code: 'AS.110.106', department: 'Mathematics' },
    { name: 'Numerical Methods', code: 'EN.553.291', department: 'Mathematics' },

    // Physics (12 courses)
    { name: 'Physics I: Mechanics', code: 'AS.171.101', department: 'Physics' },
    { name: 'Physics II: E&M', code: 'AS.171.102', department: 'Physics' },
    { name: 'Physics III: Waves and Modern', code: 'AS.171.103', department: 'Physics' },
    { name: 'Physics Lab I', code: 'AS.171.105', department: 'Physics' },
    { name: 'Physics Lab II', code: 'AS.171.106', department: 'Physics' },
    { name: 'Classical Mechanics I', code: 'AS.171.301', department: 'Physics' },
    { name: 'Electromagnetism I', code: 'AS.171.303', department: 'Physics' },
    { name: 'Modern Physics', code: 'AS.171.201', department: 'Physics' },
    { name: 'Quantum Mechanics I', code: 'AS.171.401', department: 'Physics' },
    { name: 'Thermodynamics', code: 'AS.171.304', department: 'Physics' },
    { name: 'Astrophysics', code: 'AS.171.221', department: 'Physics' },
    { name: 'Biophysics', code: 'AS.250.201', department: 'Physics' },

    // Chemistry (12 courses)
    { name: 'General Chemistry I', code: 'AS.030.103', department: 'Chemistry' },
    { name: 'General Chemistry II', code: 'AS.030.104', department: 'Chemistry' },
    { name: 'Organic Chemistry I', code: 'AS.030.205', department: 'Chemistry' },
    { name: 'Organic Chemistry II', code: 'AS.030.206', department: 'Chemistry' },
    { name: 'Physical Chemistry I', code: 'AS.030.307', department: 'Chemistry' },
    { name: 'Physical Chemistry II', code: 'AS.030.308', department: 'Chemistry' },
    { name: 'Analytical Chemistry', code: 'AS.030.227', department: 'Chemistry' },
    { name: 'Biochemistry I', code: 'AS.030.401', department: 'Chemistry' },
    { name: 'Biochemistry II', code: 'AS.030.402', department: 'Chemistry' },
    { name: 'Inorganic Chemistry', code: 'AS.030.309', department: 'Chemistry' },
    { name: 'Chemical Lab I', code: 'AS.030.111', department: 'Chemistry' },
    { name: 'Chemical Lab II', code: 'AS.030.112', department: 'Chemistry' },

    // Biology (12 courses)
    { name: 'General Biology I', code: 'AS.020.151', department: 'Biology' },
    { name: 'General Biology II', code: 'AS.020.152', department: 'Biology' },
    { name: 'Cell Biology', code: 'AS.020.311', department: 'Biology' },
    { name: 'Molecular Biology', code: 'AS.020.362', department: 'Biology' },
    { name: 'Genetics', code: 'AS.020.331', department: 'Biology' },
    { name: 'Ecology', code: 'AS.020.385', department: 'Biology' },
    { name: 'Evolution', code: 'AS.020.371', department: 'Biology' },
    { name: 'Vertebrate Anatomy', code: 'AS.020.307', department: 'Biology' },
    { name: 'Plant Biology', code: 'AS.020.321', department: 'Biology' },
    { name: 'Microbiology', code: 'AS.020.301', department: 'Biology' },
    { name: 'Neuroscience Foundations', code: 'AS.080.101', department: 'Neuroscience' },
    { name: 'Developmental Biology', code: 'AS.020.303', department: 'Biology' },

    // English and Writing (11 courses)
    { name: 'Academic Writing', code: 'AS.220.101', department: 'Writing' },
    { name: 'Poetry Writing', code: 'AS.220.201', department: 'Writing' },
    { name: 'Prose Writing', code: 'AS.220.202', department: 'Writing' },
    { name: 'American Literature I', code: 'AS.060.151', department: 'English' },
    { name: 'American Literature II', code: 'AS.060.152', department: 'English' },
    { name: 'British Literature I', code: 'AS.060.161', department: 'English' },
    { name: 'British Literature II', code: 'AS.060.162', department: 'English' },
    { name: 'Shakespeare', code: 'AS.060.220', department: 'English' },
    { name: 'World Literature', code: 'AS.060.175', department: 'English' },
    { name: 'Modern American Fiction', code: 'AS.060.251', department: 'English' },
    { name: 'Literary Theory', code: 'AS.060.311', department: 'English' },

    // History (10 courses)
    { name: 'World History I', code: 'AS.100.110', department: 'History' },
    { name: 'World History II', code: 'AS.100.111', department: 'History' },
    { name: 'American History I', code: 'AS.100.121', department: 'History' },
    { name: 'American History II', code: 'AS.100.122', department: 'History' },
    { name: 'European History I', code: 'AS.100.131', department: 'History' },
    { name: 'European History II', code: 'AS.100.132', department: 'History' },
    { name: 'Asian History', code: 'AS.100.141', department: 'History' },
    { name: 'History of Science', code: 'AS.140.105', department: 'History' },
    { name: 'African History', code: 'AS.100.151', department: 'History' },
    { name: 'Latin American History', code: 'AS.100.152', department: 'History' },
  ],
}

module.exports = { COURSES_MAJOR }
