const SCHOOLS = [
  // PUBLIC 4-YEAR (University System of Maryland)
  {
    name: 'University of Maryland, College Park',
    short: 'UMD',
    city: 'College Park',
    state: 'MD',
    schoolType: 'public',
  },
  {
    name: 'University of Maryland, Baltimore County',
    short: 'UMBC',
    city: 'Baltimore',
    state: 'MD',
    schoolType: 'public',
  },
  { name: 'Towson University', short: 'TU', city: 'Towson', state: 'MD', schoolType: 'public' },
  {
    name: 'Morgan State University',
    short: 'Morgan',
    city: 'Baltimore',
    state: 'MD',
    schoolType: 'public',
  },
  {
    name: 'Bowie State University',
    short: 'Bowie',
    city: 'Bowie',
    state: 'MD',
    schoolType: 'public',
  },
  {
    name: 'Coppin State University',
    short: 'Coppin',
    city: 'Baltimore',
    state: 'MD',
    schoolType: 'public',
  },
  {
    name: 'Salisbury University',
    short: 'SU',
    city: 'Salisbury',
    state: 'MD',
    schoolType: 'public',
  },
  {
    name: 'Frostburg State University',
    short: 'FSU',
    city: 'Frostburg',
    state: 'MD',
    schoolType: 'public',
  },
  {
    name: 'University of Baltimore',
    short: 'UBalt',
    city: 'Baltimore',
    state: 'MD',
    schoolType: 'public',
  },
  {
    name: 'University of Maryland Eastern Shore',
    short: 'UMES',
    city: 'Princess Anne',
    state: 'MD',
    schoolType: 'public',
  },
  {
    name: 'University of Maryland Global Campus',
    short: 'UMGC',
    city: 'Adelphi',
    state: 'MD',
    schoolType: 'public',
  },

  // OTHER PUBLIC
  {
    name: "St. Mary's College of Maryland",
    short: 'SMCM',
    city: "St. Mary's City",
    state: 'MD',
    schoolType: 'public',
  },
  {
    name: 'United States Naval Academy',
    short: 'USNA',
    city: 'Annapolis',
    state: 'MD',
    schoolType: 'public',
  },

  // PRIVATE
  {
    name: 'Johns Hopkins University',
    short: 'JHU',
    city: 'Baltimore',
    state: 'MD',
    schoolType: 'private',
  },
  {
    name: 'Loyola University Maryland',
    short: 'Loyola',
    city: 'Baltimore',
    state: 'MD',
    schoolType: 'private',
  },
  {
    name: 'McDaniel College',
    short: 'McDaniel',
    city: 'Westminster',
    state: 'MD',
    schoolType: 'private',
  },
  { name: 'Hood College', short: 'Hood', city: 'Frederick', state: 'MD', schoolType: 'private' },
  { name: 'Goucher College', short: 'Goucher', city: 'Towson', state: 'MD', schoolType: 'private' },
  {
    name: "Mount St. Mary's University",
    short: 'MSM',
    city: 'Emmitsburg',
    state: 'MD',
    schoolType: 'private',
  },
  {
    name: 'Washington College',
    short: 'WashCol',
    city: 'Chestertown',
    state: 'MD',
    schoolType: 'private',
  },
  {
    name: 'Stevenson University',
    short: 'Stevenson',
    city: 'Stevenson',
    state: 'MD',
    schoolType: 'private',
  },
  {
    name: 'Notre Dame of Maryland University',
    short: 'NDMU',
    city: 'Baltimore',
    state: 'MD',
    schoolType: 'private',
  },

  // COMMUNITY COLLEGES
  { name: 'Montgomery College', short: 'MC', city: 'Rockville', state: 'MD', schoolType: 'public' },
  {
    name: "Prince George's Community College",
    short: 'PGCC',
    city: 'Largo',
    state: 'MD',
    schoolType: 'public',
  },
  {
    name: 'Community College of Baltimore County',
    short: 'CCBC',
    city: 'Baltimore',
    state: 'MD',
    schoolType: 'public',
  },
  {
    name: 'Anne Arundel Community College',
    short: 'AACC',
    city: 'Arnold',
    state: 'MD',
    schoolType: 'public',
  },
  {
    name: 'Howard Community College',
    short: 'HCC',
    city: 'Columbia',
    state: 'MD',
    schoolType: 'public',
  },
  {
    name: 'Frederick Community College',
    short: 'FCC',
    city: 'Frederick',
    state: 'MD',
    schoolType: 'public',
  },
  {
    name: 'Harford Community College',
    short: 'Harford',
    city: 'Bel Air',
    state: 'MD',
    schoolType: 'public',
  },
  {
    name: 'Carroll Community College',
    short: 'Carroll',
    city: 'Westminster',
    state: 'MD',
    schoolType: 'public',
  },
  {
    name: 'College of Southern Maryland',
    short: 'CSM',
    city: 'La Plata',
    state: 'MD',
    schoolType: 'public',
  },
]

module.exports = { SCHOOLS }
